spring:
  application:
    name: store

  datasource:
    url: jdbc:postgresql://localhost:5432/qima_store
    username: femow
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
