server:
  port: 35101

spring:
  application:
    name: store

  datasource:
    url: jdbc:postgresql://localhost:5432/qima_store
    schema: qimastore
    username: femow
    password:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/qima_store
    user: femow
    password:
    schemas: qimastore
    locations: classpath:db/migrations

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: qimastore
