CREATE TABLE PRODUCT (
    ID                  INT NOT NULL,
    NAME                VARCHAR(255) NOT NULL,
    DESCRIPTION         VARCHAR(255) NOT NULL,
    PRICE               DOUBLE PRECISION NOT NULL,
    QUANTITY            INT NOT NULL,
    FK_CATEGORY         INT NOT NULL,
    CREATED_ON          TIMESTAMP NOT NULL,
    UPDATED_ON          TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_CATEGORY) REFERENCES CATEGORY(ID)
);

CREATE SEQUENCE SEQ_PRODUCT START WITH 1 INCREMENT BY 1;